### ISSUE TITLE
Modifying Path Selection based on Country-Position

### ISSUE THREAD

**Issue by ghost** [mohsen-imani/Faster-Tor-Modified-Relay-Circuit-Selection#1]
Hello.
I first appreciate the work you have  done here, it is amazing.
I just wanted to know that if we needed to consider a Country-Code for each position -> entry, middle and exit, Which portions of the code I should start to hack?
Thanks in advance.

**Comment by mohsen-imani** [comment]
Thanks much, for the entry and exit position in the circuits you don't need to change the code, it has already been considered in the Tor. You just need to tell the Tor using ExitNodes and EntryNodes options in torrc, something like ExitNodes {us}, it includes all the exit relays in the US in the exit selection.
Please check Tor manual: https://www.torproject.org/docs/tor-manual.html.en

Let me know if this doesn't work for you.

**Comment by ghost** [comment]
Hello there! 
First, thanks for your kind support and the answer.
Second, my intention of asking for this feature is this:
As you have seen the torflow project -> CircuitAnalysis -> OPAddon:
https://github.com/DonnchaC/torflow/tree/master/CircuitAnalysis/OPAddon
back in there, they have offered a feature like this:
entry_country = {{entry}}
middle_country = {{middle}}
exit_country = {{exit}}
the problem is that it does not suit production purposes, and I have implemented this feature along with stem library and other controller libraries like txtorcon; the problem i faced is that non of them is suitable for production and as long as we enable __LeaveStreamsUnatached option, tor will not function so well.
So i decided to hack the source for producing this functionality right in tor, without the help of controllers.
Thanks in advance.

**Comment by mohsen-imani** [comment]
Each node in the code has an attribute for its country code, this attribute is node->country.

https://github.com/mohsen-imani/Faster-Tor-Modified-Relay-Circuit-Selection/blob/03c46eeae3b548756f9ef207aea76cc28052a3a5/mytors/all-in-one-2.5.12/src/or/or.h#L2341


This attribute is an integer, to find out the mapping between 2-letter country codes to the integers, check file geoip.c.

The other way is to add a new attribute to the nodes in the code, add a new attribute to node_t in or.h and assign value this attribute. Use a library like GeoIP.c that we used in this work to find the country code for each node from its IP. To get the idea about how you can do this, check out our code here,

https://github.com/mohsen-imani/Faster-Tor-Modified-Relay-Circuit-Selection/blob/03c46eeae3b548756f9ef207aea76cc28052a3a5/mytors/all-in-one-2.5.12/src/or/nodelist.c#L260

This code will help you to get the idea on how you can assign value to your defined attribute. We defined two attributes 'lat' and 'long' for each node (node_t in or.h) and assigned the values to them in this part of the code.


After having the CC for each node, you can filter out the unwanted relays based on their country codes  in the following function in src/or/routerlist.c

```
static int compute_weighted_bandwidths(const smartlist_t *sl,
                            bandwidth_weight_rule_t rule,
                            u64_dbl_t **bandwidths_out)
```


In this function there is a loop:

`SMARTLIST_FOREACH_BEGIN(sl, const node_t *, node) { `

you can filter out the unwanted relays in this loop based on their country codes. In the function you have the role of the relays selection by `bandwidth_weight_rule_t rule`, exit selection, middle selection or entry selection. Be more careful in guard selection because guards are selected at the very beginning and chosen from the selected directory servers.

If this is not enough,  you may also work on these functions in file src/or/circuitbuild.c

```
static const node_t *choose_good_exit_server_general(int need_uptime, int need_capacity)

```

```
static const node_t *choose_good_middle_server(uint8_t purpose,
                          cpath_build_state_t *state,
                          crypt_path_t *head,
                          int cur_len)

```


```
const node_t  *choose_good_entry_server(uint8_t purpose, cpath_build_state_t *state)

```

Let me know if you have any questions.

**Comment by ghost** [comment]
I must appreciate for your kind and very helpful answer dear @mohsen-imani 👍  it is exactly what i was looking for. Thanks in advance.
